### ISSUE TITLE
after adding mosquitto auth plugin pub-sub not working

### ISSUE THREAD

**Issue by mkj-git** [jpmens/mosquitto-auth-plug#124]
Here i am publishing message

```
mosquitto_pub -d -t 'hello/world' -p 1884 -m 'aaaa' -u u1 -P 0123456789
Client mosqpub/27644-manish-Le sending CONNECT
Client mosqpub/27644-manish-Le received CONNACK
Client mosqpub/27644-manish-Le sending PUBLISH (d0, q0, r0, m1, 'hello/world', ... (4 bytes))
Client mosqpub/27644-manish-Le sending DISCONNECT
```

Here i am subscribing

```
 mosquitto_sub -d -t "hello/world" -p 1884 -u u1 -P 0123456789

Client mosqsub/27624-manish-Le sending CONNECT
Client mosqsub/27624-manish-Le received CONNACK
Client mosqsub/27624-manish-Le sending SUBSCRIBE (Mid: 1, Topic: hello/world, QoS: 0)
Client mosqsub/27624-manish-Le received SUBACK
Subscribed (mid: 1): 0
Client mosqsub/27624-manish-Le sending PINGREQ
Client mosqsub/27624-manish-Le received PINGRESP
```

as you can see no message has received

**Comment by kuroei** [comment]
hi, i got the same problem.

i use the http plugin for my mosquitto. but if i publish next message after 2 mins, the `Sub` client can not receive any messages yet. 

But it also might be a bugs of mosquitto because i find there is any logs about `mosquitto_auth_acl_check`, it means the mosquitto never called the interface of `acl_check`.

is there someone who get the same problem? and How cloud we fix it?

**Comment by jpmens** [comment]
I don't know what you are telling me. Check your ACLs.

**Comment by roobytwo** [comment]
I was having the same issue. As said above, check your acls, and or use an appropriate password and username in the `mosquitto_sub` command.

example:
```
mosquitto_sub -u foo@foo.com -P secretpassword -t \$SYS/broker/publish/messages/dropped
```
