### ISSUE TITLE
Probleme with mongo auth plugin 

### ISSUE THREAD

**Issue by kSuccess** [jpmens/mosquitto-auth-plug#204]
hi all 
when i run "sudo  monsquitto -c /etc/mosquitto/mosquitto.conf"
it show me that :
 1488799036: |-- *** auth-plug: startup
1488799036: |-- ** Configured order: mongo
my "mosquitto.conf" : 
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
auth_opt_backends mongo
auth_plugin /home/mouad/Desktop/mosquitto_plugin/mosquitto-auth-plug-master/auth-plug.so
auth_opt_mongo_host localhost
auth_opt_mongo_port 27017
auth_opt_mongo_user mouad
auth_opt_mongo_password linux
auth_opt_mongo_database mqGate
auth_opt_mongo_collection_users users
auth_opt_mongo_collection_topics topics
listener 1883
 but when i look into the mongoDB   there is no mqGate database !!!
> show dbs
admin  (empty)
local  0.078GB
>

**Comment by bitfreak25** [comment]
Please rethink about what you want to get. A collection (what you mean with database) in mongoDB normally will be created, when the first entry is done. So an empty collection isn't needed. You can write an entry to the database and a collection will be automatically created.

**Comment by mouaadd** [comment]
i think when i will execute the command "mosquitto -c /etc/mosquitto/mosquitto.conf"
it will create the database "mqGate" according to my configuration file described above

**Comment by bitfreak25** [comment]
Your configuration in mosquitto.conf is necessary to **connect** to the Database itself. I is not written to the Database. To **create** users and so on, you have to write into "mqGate" with the format described in [the documentation for mongodb with auth-plugin](https://github.com/jpmens/mosquitto-auth-plug#mongodb).

When you only want to create hard-coded users, that you can not change since runtime, you maybe don't need the plugin and use the [buildin authentication from mosquitto](http://mosquitto.org/man/mosquitto_passwd-1.html) itself.

**Comment by mouaadd** [comment]
ok thank's
