### ISSUE TITLE
Combine acl_file and back-ends' ACL check

### ISSUE THREAD

**Issue by fabiocapsouza** [jpmens/mosquitto-auth-plug#216]
In the project I'm using this plugin, I need to perform a basic ACL that is a pattern
+/%u/#
that forces the second level of the topic to be equal to the user's name. This type of ACL is done in one line using the acl_file option of mosquitto.conf, whereas using PostgreSQL back-end, I have to insert this ACL row for every user.
I tried using both of them at the same time, but it appears that the plugin ignores the acl_file.
I believe it would be a nice feature to use both the acl_file (to include pattern ACL) and the plugin itself at the same time.

**Comment by rh389** [comment]
The immediate issue here is on mosquitto's side. The ACL file is only used as a fallback if no auth plugin is specified: https://github.com/eclipse/mosquitto/blob/master/src/security.c#L189. I see three options:

1. Duplicate the ACL file parser and logic into into `mosquitto-auth-plug` as a new backend.
2. Expose the `acl_file` functions as part of the public API of `mosquitto`, so that `mosquitto-auth-plug` can use it as a backend without duplicating the implementation.
2. Add support in `mosquitto` for combining an `acl_file` with an `auth_plugin`.

The first option seems fragile to me, the latter two are neater but require changes over on `mosquitto` first.

For your issue though, you might be able to support this with a clever ACL query:
1. Set `aclquery` to `SELECT topic FROM acls WHERE ((username = '%s') OR (username = 'authenticated_user')) AND (rw >= %d)`
2. Insert a single row into your ACL table with username `authenticated_user` and topic `+/%u/#`.

This should work because the postgres backend fetches all rows matching `aclquery`, then expands each returned topic, replacing `%u` with the username, before checking for a match against the requested topic.

(Replace `'authenticated_user'` with a string of your choice, but make sure it's a reserved name in your app)
